# Generated by Django 2.2.1 on 2020-01-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'М'), ('W', 'Ж')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(db_index=True, max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Отчество')),
                ('amb_card', models.IntegerField(unique=True, verbose_name='Номер абулаторной карты')),
                ('employee_lastName', models.CharField(max_length=30, verbose_name='Фамили')),
                ('place_of_residence', models.CharField(max_length=100, verbose_name='Место жительства')),
                ('place_of_study', models.CharField(max_length=100, verbose_name='Место работы/учебы')),
                ('number_passport', models.CharField(max_length=12, verbose_name='номер паспорта')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dentistry.Gender', verbose_name='Пол')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
