# Generated by Django 2.2.1 on 2020-01-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentistry', '0003_auto_20200113_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название должности')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], default=0, max_length=10, verbose_name='Вид лечения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='amb_card',
            field=models.IntegerField(verbose_name='Номер амбулаторной карты'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastName',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(help_text='Фамиля Сотрудника', max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Имя Сотрудника', max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_index=True, help_text='Отчество Сотрудника', max_length=30, null=True, verbose_name='Отчество')),
                ('position', models.ForeignKey(help_text='название должности', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='dentistry.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.IntegerField(verbose_name='Страховой полис')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dentistry.Employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='dentistry.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admission_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница')], max_length=20, verbose_name='День недели')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_time', to='dentistry.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=100, verbose_name='Причина визита')),
                ('time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='dentistry.Employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='dentistry.Patient')),
            ],
        ),
    ]
